name: 'AWS SAM GitHub Actions [node12]'
description: 'Runs AWS-SAM via GitHub Actions.'
author: 'Gabriel Gordo'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  sam_version:
    description: 'AWS SAM version to install.'
    default: 'latest'
  sam_command:
    description: 'AWS SAM subcommand to execute.'
    required: true
  actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: false
runs:
  using: 'docker'
  image: './Dockerfile'