name: Push CI

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    name: build node
    runs-on: ubuntu-latest
    steps:
    - name: Checkot
      uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run npm install
      run: |
        cd src
        npm install
        cd ..
    - name: Checkout
      uses: actions/checkout@master
    - name: sam build
      uses: Gabriel-Acevedo/tfm-aws/node12@master
      with:
        sam_command: build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
