name: Push CI

on:
  push:
    branches: [ master ]
  
jobs:
  setup_node:
    name: build node
    runs-on: ubuntu-latest
    steps:
    - name: Checkot
      uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run npm install
      run: |
        cd src
        npm install
        cd ..
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew --version
        sam build
        sam deploy --no-confirm-changeset
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}sam deploy