name: "CD: Publish Release and Zip Files"

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'V*'
  
jobs:
  release_version:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Get the current version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Zip Application Data
        run: |
          zip -r release-${{ steps.get_version.outputs.VERSION }}.zip . -x ".git/*" ".github/*" ".aws-sam/*"
      - name: Release to Github
        run: echo "Release ${{ steps.get_version.outputs.VERSION }}"
      - name: Upload Zip file to AWS
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: release-${{ steps.get_version.outputs.VERSION }}.zip
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ secrets.AWS_RELEASE_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  setup_node:
    name: Setup Node 12
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run npm install
      run: |
        cd src
        npm install
        cd ..
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        
        
  execute_sam:
    name: Build and Deploy SAM
    runs-on: ubuntu-latest
    needs: [setup_node]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Deploy SAM
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        sam build
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      
#  testing_endpoint:
#    name: Testing Endpoints
#    runs-on: ubuntu-latest
#    needs: [execute_sam]
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2      
#    - name: Testing API REST
#      run: |
#        curl -v ${{ secrets.AWS_REST_API_ENDPOINT }}/api/customers 
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
