name: "CI: Publish Release and Zip Files"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  release_version:
    name: Create Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download S3 File
        uses: prewk/s3-cp-action@master
        env:
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FILE: release-${{ steps.get_version.outputs.VERSION }}.zip
          SOURCE: 's3://aws-artefacts-lambdas-tfm-aws/release-v1.1.4.zip'
          DEST: './release-v1.1.4.zip'